# Generated by Django 4.2.9 on 2024-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projint', '0002_rename_name_mydata_trade_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='close',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='high',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='low',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='open',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='volume',
            field=models.CharField(max_length=255),
        ),
    ]
